<?xml version="1.0" encoding="utf-8"?><Database Name="LRM" Class="LRMDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=DESKTOP-9H682VS;Initial Catalog=LRM;Persist Security Info=True;User ID=sa" SettingsObjectName="__LRM.Properties.Settings" SettingsPropertyName="LRMConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.Room" Member="Rooms">
    <Type Name="Room">
      <Column Name="Room_ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Room_Name" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="Building" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="Floors" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Association Name="Room_Computer" Member="Computers" ThisKey="Room_ID" OtherKey="Room_ID" Type="Computer" />
    </Type>
  </Table>
  <Table Name="dbo.Computer" Member="Computers">
    <Type Name="Computer">
      <Column Name="Computer_ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="CPU" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="Hard_Disk" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="RAM" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="VGA" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Monitor" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Room_Name" Type="System.String" DbType="NVarChar(150)" CanBeNull="true" />
      <Column Name="Room_ID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="Room_Computer" Member="Room" ThisKey="Room_ID" OtherKey="Room_ID" Type="Room" IsForeignKey="true" />
    </Type>
  </Table>
</Database>